version: '3'

services:
  flask_app:
    build: ./flask_app
    ports:
      - "8000"
    command: gunicorn -b 0.0.0.0:8000 wsgi:server
  

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app
  
   
  redis:
    image: redis
    ports:
      - "6379:6379"
    